In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import OneHotEncoder, LabelEncoder
from sklearn.preprocessing import StandardScaler
import sklearn.datasets as Datasets
import statsmodels.formula.api as sm
from sklearn.linear_model import LinearRegression
from sklearn import model_selection as cv

In [2]:
titanic_train = pd.read_csv("../data/Kaggle/Titanic/train.csv")
titanic_test = pd.read_csv("../data/Kaggle/Titanic/test.csv")
del titanic_train["PassengerId"]
del titanic_train["Name"]
del titanic_train["Ticket"]
del titanic_train["Cabin"]
del titanic_test["PassengerId"]
del titanic_test["Name"]
del titanic_test["Ticket"]
del titanic_test["Cabin"]

In [3]:
print(titanic_train.describe())
titanic_test.describe()
#now need to remove nan values from test and train data

         Survived      Pclass         Age       SibSp       Parch        Fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200


Pclass         Age       SibSp       Parch        Fare
count  418.000000  332.000000  418.000000  418.000000  417.000000
mean     2.265550   30.272590    0.447368    0.392344   35.627188
std      0.841838   14.181209    0.896760    0.981429   55.907576
min      1.000000    0.170000    0.000000    0.000000    0.000000
25%      1.000000   21.000000    0.000000    0.000000    7.895800
50%      3.000000   27.000000    0.000000    0.000000   14.454200
75%      3.000000   39.000000    1.000000    0.000000   31.500000
max      3.000000   76.000000    8.000000    9.000000  512.329200

In [4]:
survived_mean_age = titanic_train[(pd.isnull(titanic_train.Age)==False) & titanic_train.Survived == 1].Age.mean()
print("Survived mean age in taininig data is = ",survived_mean_age)
not_survived_mean_age = titanic_train[(pd.isnull(titanic_train.Age)==False) & titanic_train.Survived == 0].Age.mean()
print("Not Survived mean age in taininig data is = ",not_survived_mean_age)

Survived mean age in taininig data is =  28.343689655172415
Not Survived mean age in taininig data is =  30.62617924528302


In [5]:
titanic_train.loc[pd.isnull(titanic_train.Age) & (titanic_train.Survived == 1),'Age'] = survived_mean_age
titanic_train.loc[pd.isnull(titanic_train.Age) & (titanic_train.Survived == 0),'Age'] = not_survived_mean_age

titanic_test.loc[pd.isnull(titanic_test.Age),'Age'] = titanic_test.Age.mean()
titanic_test.loc[pd.isnull(titanic_test.Fare),'Fare'] = titanic_test.Fare.mean()

In [6]:
print(titanic_test.describe())
titanic_test.head()

           Pclass         Age       SibSp       Parch        Fare
count  418.000000  418.000000  418.000000  418.000000  418.000000
mean     2.265550   30.272590    0.447368    0.392344   35.627188
std      0.841838   12.634534    0.896760    0.981429   55.840500
min      1.000000    0.170000    0.000000    0.000000    0.000000
25%      1.000000   23.000000    0.000000    0.000000    7.895800
50%      3.000000   30.272590    0.000000    0.000000   14.454200
75%      3.000000   35.750000    1.000000    0.000000   31.500000
max      3.000000   76.000000    8.000000    9.000000  512.329200


Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0       3    male  34.5      0      0   7.8292        Q
1       3  female  47.0      1      0   7.0000        S
2       2    male  62.0      0      0   9.6875        Q
3       3    male  27.0      0      0   8.6625        S
4       3  female  22.0      1      1  12.2875        S

In [7]:
print(titanic_train.describe())
titanic_train.head()

         Survived      Pclass         Age       SibSp       Parch        Fare
count  891.000000  891.000000  891.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.750072    0.523008    0.381594   32.204208
std      0.486592    0.836071   13.010682    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   22.000000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   30.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   35.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200


Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

In [8]:
titanic_train.dropna(inplace = True) #Dropping where embarked = Nan

In [9]:
from sklearn.preprocessing import OneHotEncoder,LabelEncoder
X_train = titanic_train.values[:,1:]
Y_train = titanic_train.values[:,0].astype(int)
X_test = titanic_test.values[:,0:]

In [10]:
#Label Encoding

labelEncoder_gender = LabelEncoder()
labelEncoder_port = LabelEncoder()
print(X_train[0])
print(X_test[0])
X_train[:,1] = labelEncoder_gender.fit_transform(X_train[:,1])
X_test[:,1] = labelEncoder_gender.transform(X_test[:,1])
X_train[:,6] = labelEncoder_port.fit_transform(X_train[:,6])
X_test[:,6] = labelEncoder_port.transform(X_test[:,6])
print(X_train[0])
print(X_test[0])

[3 'male' 22.0 1 0 7.25 'S']
[3 'male' 34.5 0 0 7.8292 'Q']
[3 1 22.0 1 0 7.25 2]
[3 1 34.5 0 0 7.8292 1]


In [11]:
#One Hot Encoding

oneHotEncoder = OneHotEncoder(categorical_features = [0,6]) #Not including gender as it only has 2 values
X_train = oneHotEncoder.fit_transform(X_train).toarray()
X_test = oneHotEncoder.transform(X_test).toarray()
print(X_train[0])
print(X_test[0])
X_train = np.delete(X_train, 2, 1)
X_train = np.delete(X_train, 4, 1)
X_test = np.delete(X_test, 2, 1)
X_test = np.delete(X_test, 4, 1)
print(X_train[0])
print(X_test[0])

[  0.     0.     1.     0.     0.     1.     1.    22.     1.     0.     7.25]
[  0.       0.       1.       0.       1.       0.       1.      34.5      0.
   0.       7.8292]
[  0.     0.     0.     0.     1.    22.     1.     0.     7.25]
[  0.       0.       0.       1.       1.      34.5      0.       0.
   7.8292]


In [12]:
#Feature Scaling
from sklearn.preprocessing import StandardScaler

sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)
print(X_train[0])
print(X_test[0])

[-0.56306042 -0.51087465 -0.48271079 -0.30794088  0.73534203 -0.59402797
  0.43135024 -0.47432585 -0.50023975]
[-0.56306042 -0.51087465 -0.48271079  3.24737656  0.73534203  0.36973797
 -0.47519908 -0.47432585 -0.48857868]


In [13]:
# from sklearn.linear_model import LogisticRegression

# classifier = LogisticRegression(random_state=0)
# classifier.fit(X_train,Y_train)
# pred_y_train = classifier.predict(X_train)

from sklearn.ensemble import RandomForestClassifier

classifier = RandomForestClassifier(n_estimators=10000, criterion = "entropy", random_state=0)
classifier.fit(X_train,Y_train)
pred_y_train = classifier.predict(X_train)

In [14]:
def accuracy(predicted_result,actual_result):
    count = 0
    for i in range(0,len(predicted_result)):
        if(int(predicted_result[i]) == actual_result[i]):
            count = count + 1
    return (count/len(predicted_result))

In [15]:
accuracy(classifier.predict(X_train),Y_train)

0.9887514060742407

In [16]:
Y_pred = classifier.predict(X_test)
result = pd.DataFrame()
result["PassengerId"] = np.arange(892,892+418)

In [17]:
result["Survived"] = Y_pred

In [18]:
result.to_csv("../data/Kaggle/Titanic/Y_test.csv",index = False)